import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";
import HeadScripts, { BodyScripts } from "@/components/scripts";

const dmSans = DM_Sans({
  // variable: "--font-dm-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "700", "800", "900", "1000"],
});

export const metadata: Metadata = {
  title: "Lumio AI",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <HeadScripts />
        <link
            rel="icon"
            href="/images/logos/favicon-light.ico"
            media="(prefers-color-scheme: light)"
          />
          {/* Favicon for Dark Mode */}
          <link
            rel="icon"
            href="/images/logos/favicon-dark.ico"
            media="(prefers-color-scheme: dark)"
          />
      </head>
      <body className={`${dmSans.className} antialiased`}>
        <Header />
        {children}
        <Footer />
        <BodyScripts />
      </body>
    </html>
  );
}
